# Generated by Django 3.1.5 on 2021-02-17 03:10

import django.db.models.deletion
from django.db import migrations, models

import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0059_apply_collection_ordering"),
        ("hip", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "quick_links",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "quick_links",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="The linked text that will be visible to the reader",
                                                max_length=255,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "link_url",
                                            wagtail.core.blocks.URLBlock(
                                                help_text="The URL to link to",
                                                max_length=255,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "text",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="Text below the title ",
                                                max_length=255,
                                                required=True,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                    ),
                ),
                ("about", wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
