# Generated by Django 3.1.5 on 2021-02-13 19:12

from django.db import migrations

import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hip", "0002_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="about",
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
