# Generated by Django 3.1.5 on 2021-02-19 01:10

import django.core.validators
from django.db import migrations, models

import apps.hip.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('hip', '0003_quicklinks_internal_or_external'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_hours_call_number', models.CharField(help_text='Business Hours Call Number', max_length=12, validators=[django.core.validators.RegexValidator(message='Please provide a valid phone number', regex='^\\(?([0-9]{3})\\)?[-.●]?([0-9]{3})[-.●]?([0-9]{4})$')])),
                ('business_hours_fax_number', models.CharField(help_text='Business Hours Fax Number', max_length=12, validators=[django.core.validators.RegexValidator(message='Please provide a valid phone number', regex='^\\(?([0-9]{3})\\)?[-.●]?([0-9]{3})[-.●]?([0-9]{4})$')])),
                ('after_hours_call_number', models.CharField(help_text='After Hours Call Number', max_length=12, validators=[django.core.validators.RegexValidator(message='Please provide a valid phone number', regex='^\\(?([0-9]{3})\\)?[-.●]?([0-9]{3})[-.●]?([0-9]{4})$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='body',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('nav_heading', wagtail.core.blocks.CharBlock(help_text='The heading that should appear for this section in the scrolling navigation on the side of the page.', max_length=80, required=False)), ('is_card', wagtail.core.blocks.BooleanBlock(help_text='Is this content block a card?', required=False)), ('body', wagtail.core.blocks.StreamBlock([('rich_text', wagtail.core.blocks.RichTextBlock()), ('two_column_table', wagtail.core.blocks.StructBlock([('has_grid_pattern', wagtail.core.blocks.BooleanBlock(help_text="Does this table's styling have a grid pattern?", required=False)), ('is_first_row_header', wagtail.core.blocks.BooleanBlock(help_text='Should the first row be displayed as a header?', required=False)), ('rows', wagtail.core.blocks.StreamBlock([('rows', wagtail.core.blocks.StructBlock([('column_1', wagtail.core.blocks.RichTextBlock(help_text='Text for column 1', max_length=255, required=False)), ('column_2', wagtail.core.blocks.RichTextBlock(help_text='Text for column 2', max_length=255, required=False))]))]))]))])), ('contact_info', wagtail.snippets.blocks.SnippetChooserBlock(apps.hip.models.Contact, required=False))]))]),
        ),
    ]
