# Generated by Django 3.1.6 on 2021-02-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hip', '0004_auto_20210223_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
