# Generated by Django 3.1.6 on 2021-02-23 02:32

from django.db import migrations

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hip', '0004_auto_20210223_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='quick_links',
            field=wagtail.fields.StreamField([('quick_links', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='The linked text that will be visible to the reader', max_length=255, required=True)), ('link_page', wagtail.blocks.PageChooserBlock(help_text='An internal page', required=False)), ('link_url', wagtail.blocks.URLBlock(help_text='An external URL (if not linking to an internal page)', max_length=255, required=False)), ('updated_on', wagtail.blocks.DateBlock(help_text='If the link is to an external URL, this will be the displayed as the updated date', required=False))]))], blank=True),
        ),
    ]
