# Generated by Django 3.1.6 on 2021-02-23 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hip', '0005_auto_20210223_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hip.contact'),
        ),
    ]
