# Generated by Django 3.1.6 on 2021-03-10 17:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('hip', '0007_auto_20210223_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaticPage',
            new_name='ReportDiseasePage',
        ),
    ]
