# Generated by Django 3.1.6 on 2021-03-31 19:17

import django.db.models.deletion
from django.db import migrations, models

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
        ("hip", "0009_add_staticpage_four_column_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "show_right_nav",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Should this page show a navigation of its sections on the right side of the page?",
                    ),
                ),
                (
                    "list_section",
                    wagtail.fields.StreamField(
                        [
                            (
                                "list_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "header",
                                            wagtail.blocks.CharBlock(
                                                help_text="The heading for this section of rows (maximum of 80 characters).",
                                                max_length=80,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "show_header_in_right_nav",
                                            wagtail.blocks.BooleanBlock(
                                                default=True,
                                                help_text="Should this header be shown in the navigation on the right side of the page?",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "rows",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "rows",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "page",
                                                                    wagtail.blocks.PageChooserBlock(
                                                                        help_text="An internal page",
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "description",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        help_text="Description for this row",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    )
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
