# Generated by Django 3.1.6 on 2021-03-30 23:10

import django.db.models.deletion
from django.db import migrations, models

import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('hip', '0009_add_staticpage_four_column_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleDetailPageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Simple Detail Page Category',
                'verbose_name_plural': 'Simple Detail Page Categories',
            },
        ),
        migrations.CreateModel(
            name='SimpleListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('page_customization', wagtail.core.fields.StreamField([('disable_right_nav', wagtail.core.blocks.BooleanBlock(help_text='Remove right side navigation from this page?', required=False))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SimpleDetailPage',
            fields=[
                ('staticpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hip.staticpage')),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hip.simpledetailpagecategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('hip.staticpage',),
        ),
    ]
