# Generated by Django 3.1.6 on 2021-04-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hip", "0010_listpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="listpage",
            name="show_breadcrumb",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Should this page show a breadcrumb at the top of the page?",
            ),
        ),
    ]
