# Generated by Django 3.1.6 on 2021-03-31 02:42

from django.db import migrations

import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hip', '0011_simpledetailpage_page_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpledetailpage',
            name='page_customization',
            field=wagtail.core.fields.StreamField([('disable_right_nav', wagtail.core.blocks.BooleanBlock(default=False, help_text='Remove right side navigation from this page?'))], blank=True),
        ),
        migrations.AlterField(
            model_name='simplelistpage',
            name='page_customization',
            field=wagtail.core.fields.StreamField([('disable_right_nav', wagtail.core.blocks.BooleanBlock(default=False, help_text='Remove right side navigation from this page?'))], blank=True),
        ),
    ]
