# Generated by Django 3.1.6 on 2021-04-01 14:42

from django.db import migrations

import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hip", "0011_listpage_show_breadcrumb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listpage",
            name="list_section",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "list_section",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "header",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="The heading for this section of rows (maximum of 80 characters).",
                                        max_length=80,
                                        required=False,
                                    ),
                                ),
                                (
                                    "show_header_in_right_nav",
                                    wagtail.core.blocks.BooleanBlock(
                                        default=True,
                                        help_text="Should this header be shown in the navigation on the right side of the page?",
                                        required=False,
                                    ),
                                ),
                                (
                                    "rows",
                                    wagtail.core.blocks.StreamBlock(
                                        [
                                            (
                                                "rows",
                                                wagtail.core.blocks.StructBlock(
                                                    [
                                                        (
                                                            "page",
                                                            wagtail.core.blocks.PageChooserBlock(
                                                                help_text="An internal page",
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.core.blocks.RichTextBlock(
                                                                help_text="Description for this row",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                            )
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ]
            ),
        ),
    ]
