# Generated by Django 3.1.6 on 2021-04-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hip", "0013_staticpage_more_table_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpage",
            name="show_breadcrumb",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Should this page show a breadcrumb at the top of the page?",
            ),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="show_back_button",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Should this page show a back button at the top of the page?",
            ),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="show_left_nav",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Should this page show a navigation of the site on the left side of the page?",
            ),
        ),
        migrations.AddField(
            model_name="staticpage",
            name="show_right_nav",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Should this page show a navigation of its sections on the right side of the page?",
            ),
        ),
    ]
