# Generated by Django 3.1.6 on 2021-04-12 16:48

import django.utils.timezone
from django.db import migrations, models

import model_utils.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks

import apps.hip.models


class Migration(migrations.Migration):

    dependencies = [
        ('hip', '0014_staticpage_fields_for_nav_backbutton_and_breadcrumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('org_name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('twitter', models.URLField(blank=True, max_length=255)),
                ('facebook', models.URLField(blank=True, max_length=255)),
                ('instagram', models.URLField(blank=True, max_length=255)),
                ('youtube', models.URLField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='body',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.StructBlock([('nav_heading', wagtail.core.blocks.CharBlock(help_text='The heading that should appear for this section in the scrolling navigation on the side of the page.', max_length=80, required=False)), ('is_card', wagtail.core.blocks.BooleanBlock(help_text='Is this content block a card?', required=False)), ('body', wagtail.core.blocks.StreamBlock([('rich_text', wagtail.core.blocks.RichTextBlock()), ('two_column_table', wagtail.core.blocks.StructBlock([('has_grid_pattern', wagtail.core.blocks.BooleanBlock(help_text="Does this table's styling have a grid pattern?", required=False)), ('is_first_row_header', wagtail.core.blocks.BooleanBlock(help_text='Should the first row be displayed as a header?', required=False)), ('rows', wagtail.core.blocks.StreamBlock([('rows', wagtail.core.blocks.StructBlock([('column_1', wagtail.core.blocks.RichTextBlock(help_text='Text for column 1', max_length=255, required=False)), ('column_2', wagtail.core.blocks.RichTextBlock(help_text='Text for column 2', max_length=255, required=False)), ('social_media', wagtail.snippets.blocks.SnippetChooserBlock(apps.hip.models.SocialMedia, help_text='Social media links will be shown with this row.', required=False))]))]))])), ('three_column_table', wagtail.core.blocks.StructBlock([('has_grid_pattern', wagtail.core.blocks.BooleanBlock(help_text="Does this table's styling have a grid pattern?", required=False)), ('is_first_row_header', wagtail.core.blocks.BooleanBlock(help_text='Should the first row be displayed as a header?', required=False)), ('rows', wagtail.core.blocks.StreamBlock([('rows', wagtail.core.blocks.StructBlock([('column_1', wagtail.core.blocks.RichTextBlock(help_text='Text for column 1', max_length=255, required=False)), ('column_2', wagtail.core.blocks.RichTextBlock(help_text='Text for column 2', max_length=255, required=False)), ('column_3', wagtail.core.blocks.RichTextBlock(help_text='Text for column 3', max_length=255, required=False)), ('social_media', wagtail.snippets.blocks.SnippetChooserBlock(apps.hip.models.SocialMedia, help_text='Social media links will be shown with this row.', required=False))]))]))])), ('four_column_table', wagtail.core.blocks.StructBlock([('has_grid_pattern', wagtail.core.blocks.BooleanBlock(help_text="Does this table's styling have a grid pattern?", required=False)), ('is_first_row_header', wagtail.core.blocks.BooleanBlock(help_text='Should the first row be displayed as a header?', required=False)), ('rows', wagtail.core.blocks.StreamBlock([('rows', wagtail.core.blocks.StructBlock([('column_1', wagtail.core.blocks.RichTextBlock(help_text='Text for column 1', max_length=255, required=False)), ('column_2', wagtail.core.blocks.RichTextBlock(help_text='Text for column 2', max_length=255, required=False)), ('column_3', wagtail.core.blocks.RichTextBlock(help_text='Text for column 3', max_length=255, required=False)), ('column_4', wagtail.core.blocks.RichTextBlock(help_text='Text for column 4', max_length=255, required=False)), ('social_media', wagtail.snippets.blocks.SnippetChooserBlock(apps.hip.models.SocialMedia, help_text='Social media links will be shown with this row.', required=False))]))]))])), ('five_column_table', wagtail.core.blocks.StructBlock([('has_grid_pattern', wagtail.core.blocks.BooleanBlock(help_text="Does this table's styling have a grid pattern?", required=False)), ('is_first_row_header', wagtail.core.blocks.BooleanBlock(help_text='Should the first row be displayed as a header?', required=False)), ('rows', wagtail.core.blocks.StreamBlock([('rows', wagtail.core.blocks.StructBlock([('column_1', wagtail.core.blocks.RichTextBlock(help_text='Text for column 1', max_length=255, required=False)), ('column_2', wagtail.core.blocks.RichTextBlock(help_text='Text for column 2', max_length=255, required=False)), ('column_3', wagtail.core.blocks.RichTextBlock(help_text='Text for column 3', max_length=255, required=False)), ('column_4', wagtail.core.blocks.RichTextBlock(help_text='Text for column 4', max_length=255, required=False)), ('column_5', wagtail.core.blocks.RichTextBlock(help_text='Text for column 5', max_length=255, required=False)), ('social_media', wagtail.snippets.blocks.SnippetChooserBlock(apps.hip.models.SocialMedia, help_text='Social media links will be shown with this row.', required=False))]))]))]))])), ('contact_info', wagtail.snippets.blocks.SnippetChooserBlock(apps.hip.models.Contact, required=False))]))]),
        ),
    ]
