# Generated by Django 3.1.8 on 2021-04-20 17:42

from django.db import migrations

import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hip", "0017_hipdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpage",
            name="action_section",
            field=wagtail.core.fields.RichTextField(
                blank=True,
                help_text="This section will stand out to users, calling them to perform an action.",
            ),
        ),
    ]
