# Generated by Django 3.1.8 on 2021-06-14 19:42

from django.db import migrations
from django.shortcuts import reverse


def create_button_snippets_for_forms(apps, schema_editor):
    """Create a ButtonSnippet for each of the forms on the site, except the health alert form."""
    ButtonSnippet = apps.get_model("hip", "ButtonSnippet")

    buttons_to_be_created = [
        {
            "button_text": "Sign Up For Internal Alerts",
            "relative_url": reverse("internal_alerts_signup"),
        },
        {
            "button_text": "Sign Up For Community Notifications",
            "relative_url": reverse("community_notifications_signup"),
        },
        {
            "button_text": "Sign Up For Drug Overdose Notifications",
            "relative_url": reverse("drug_notifications_signup"),
        },
        {
            "button_text": "Sign Up For Code Blue/Code Red Notifications",
            "relative_url": reverse("codeblue_codered_notifications_signup"),
        },
        {
            "button_text": "Sign Up Public Health Preparedness Notifications",
            "relative_url": reverse("public_health_preparedness_signup"),
        },
    ]

    for button_data in buttons_to_be_created:
        ButtonSnippet.objects.get_or_create(
            button_text=button_data["button_text"],
            relative_url=button_data["relative_url"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("hip", "0021_add_buttonsnippet_to_staticpage_body"),
    ]

    operations = [
        migrations.RunPython(
            create_button_snippets_for_forms, migrations.RunPython.noop
        ),
    ]
