# Generated by Django 5.1.7 on 2025-03-19 15:01
from django.contrib.postgres.operations import CreateCollation
from django.db import migrations


# Support for CIEmailField was be depreacated after Django 4.2 in favor
# of vanilla EmailField. Below is how to migrate to the vanilla EmailField whilst
# creating a non-deterministic collation. See Adam's post for more information
# https://adamj.eu/tech/2023/02/23/migrate-django-postgresql-ci-fields-case-insensitive-collation/
class Migration(migrations.Migration):

    dependencies = [
        ("hip", "0024_alter_staticpage_body"),
    ]

    operations = [
        CreateCollation(
            "case_insensitive",
            provider="icu",
            locale="und-u-ks-level2",
            deterministic=False,
        ),
    ]
