# Generated by Django 5.2.1 on 2025-06-13 15:37

import django.db.models.deletion
from django.db import migrations, models

import django_extensions.db.fields
import modelcluster.fields
from wagtail.models import Page


def populate_menus(apps, schema_editor):
    ''' A function to setup the menu data associated with website '''
    PageLink = apps.get_model("hip", "PageLink")
    Menu = apps.get_model("hip", "Menu")
    menus_data = [
        {
            "title": "Main Menu",
            "links": [
                { 
                    "page_slug": "home",
                    "link_title": None
                },
                { 
                    "page_slug": "health-alerts",
                    "link_title": None
                },
                { 
                    "page_slug": "data-reports-statistics",
                    "link_title": None
                },
                { 
                    "page_slug": "disease-control",
                    "link_title": None
                },
                { 
                    "page_slug": "emergent-health-topics",
                    "link_title": None
                },
                { 
                    "page_slug": "emergency-response",
                    "link_title": None
                },
            ],
        },
        { 
            "title": "Resources Menu",
            "links": [
                { 
                    "page_slug": "php-community-resources",
                    "link_title": "Community Resources"
                },
                { 
                    "page_slug": "newsletters",
                    "link_title": None
                },
                { 
                    "page_slug": "posters",
                    "link_title": None
                },
                { 
                    "page_slug": "related-websites",
                    "link_title": None
                },
                { 
                    "page_slug": "emergent-health-topics",
                    "link_title": None
                },
                { 
                    "page_slug": "emergency-response",
                    "link_title": None
                },
            ],
        }
    ]

    for item in menus_data:
        menu = Menu.objects.create(title=item['title'])
        
        for index, link in enumerate(item['links']):
            if page := Page.objects.filter(slug=link['page_slug']).first():
                link_title = link['link_title'] if link['link_title'] else page.title
                PageLink.objects.create(page=menu, link_page_id=page.id, title=link_title, sort_order=index)


class Migration(migrations.Migration):

    dependencies = [
        ("hip", "0025_case_insensitive_collation"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="title"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PageLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "link_page",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_links",
                        to="hip.menu",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.RunPython(populate_menus, migrations.RunPython.noop),
    ]
