# Generated by Django 3.1.6 on 2021-03-22 11:39

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosedPODHomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "action_section",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="This section will stand out to users, calling them to perform an action.",
                    ),
                ),
                (
                    "plan_subtitle",
                    models.CharField(
                        blank=True,
                        help_text="The title of the 'Plan' section.",
                        max_length=255,
                    ),
                ),
                (
                    "plan_text",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="The text of the 'Plan' section."
                    ),
                ),
                (
                    "exercise_subtitle",
                    models.CharField(
                        blank=True,
                        help_text="The title of the 'Exercise' section.",
                        max_length=255,
                    ),
                ),
                (
                    "exercise_text",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="The text of the 'Exercise' section."
                    ),
                ),
                (
                    "about_subtitle",
                    models.CharField(
                        blank=True,
                        help_text="The title of the 'About' section.",
                        max_length=255,
                    ),
                ),
                (
                    "about_text",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="The text of the 'About' section."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
