# Generated by Django 3.1.6 on 2021-03-22 11:42

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hip", "0008_homepage_short_description"),
        ("auth_content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosedPODChildPage",
            fields=[
                (
                    "staticpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hip.staticpage",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="The description that will appear for this page on the ClosedPODHomePage.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("hip.staticpage",),
        ),
    ]
