# Generated by Django 3.1.6 on 2021-03-22 19:48

from django.db import migrations


def created_closedpod_group(apps, schema_editor):
    """Create a 'Closed POD' Group."""
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name="Closed POD")


def delete_closedpod_group(apps, schema_editor):
    """Delete a 'Closed POD' Group, if it exists."""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Closed POD").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0002_closedpodchildpage"),
    ]

    operations = [migrations.RunPython(created_closedpod_group, delete_closedpod_group)]
