# Generated by Django 3.1.6 on 2021-03-23 18:31

import django.db.models.deletion
from django.db import migrations, models

import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hip", "0008_homepage_short_description"),
        ("auth_content", "0003_closedpod_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="PCWMSAHomePage",
            fields=[
                (
                    "staticpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hip.staticpage",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, help_text="A subtitle for the page.", max_length=255
                    ),
                ),
                (
                    "action_section",
                    wagtail.core.fields.RichTextField(
                        blank=True,
                        help_text="This section will stand out to users, calling them to perform an action.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("hip.staticpage",),
        ),
    ]
