# Generated by Django 3.1.6 on 2021-03-24 00:43

from django.db import migrations


def create_pcwmsa_group(apps, schema_editor):
    """Create a 'PCW MSA' Group."""
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name="PCW MSA")


def delete_pcwmsa_group(apps, schema_editor):
    """Delete a 'PCW MSA' Group, if it exists."""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="PCW MSA").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0004_pcwmsahomepage"),
    ]

    operations = [migrations.RunPython(create_pcwmsa_group, delete_pcwmsa_group)]
