# Generated by Django 3.1.6 on 2021-04-03 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hip", "0013_staticpage_more_table_types"),
        ("auth_content", "0005_pcwmsa_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="BigCitiesHomePage",
            fields=[
                (
                    "staticpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hip.staticpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("hip.staticpage",),
        ),
    ]
