# Generated by Django 3.1.8 on 2021-04-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_content", "0008_closedpodcontactinformation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pcwmsahomepage",
            name="action_section",
        ),
    ]
