version: '3.4'

services:
  app:
    environment:
      DJANGO_SETTINGS_MODULE: hip.settings.dev
      DATABASE_URL: postgres://postgres@db:5432/hip
      CACHE_HOST: cache:11211
      ENVIRONMENT: local
      DJANGO_SECRET_KEY: insecure-dev-key
      DOMAIN: localhost
      DEBUG_TOOLBAR: "False"
      EMAIL_HOST: mailhog
      EMAIL_PORT: 1025
      SESSION_COOKIE_SECURE: "False"
    build:
      target: test
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
  cache:
    image: memcached:1.6-alpine
  mailhog:
    image: mailhog/mailhog:v1.0.0
