# Generated by Django 3.1.6 on 2021-03-10 02:12

import django.db.models.deletion
from django.db import migrations, models

import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyResponsePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("description", wagtail.core.fields.RichTextField(blank=True)),
                (
                    "action_section",
                    wagtail.core.fields.RichTextField(
                        blank=True,
                        help_text="This section will stand out to users, calling them to perform an action.",
                    ),
                ),
                (
                    "sections_of_links",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "section_of_links",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.core.blocks.CharBlock(
                                                help_text="The title for this section.",
                                                max_length=255,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "number_of_columns",
                                            wagtail.core.blocks.IntegerBlock(
                                                default=1,
                                                help_text="The number of columns in which to show this section.",
                                                max_value=2,
                                                min_value=1,
                                            ),
                                        ),
                                        (
                                            "link_blocks",
                                            wagtail.core.blocks.StreamBlock(
                                                [
                                                    (
                                                        "block_of_links",
                                                        wagtail.core.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "subtitle",
                                                                    wagtail.core.blocks.CharBlock(
                                                                        help_text="The subtitle for this block of links.",
                                                                        max_length=255,
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "text",
                                                                    wagtail.core.blocks.RichTextBlock(),
                                                                ),
                                                            ],
                                                            blank=True,
                                                        ),
                                                    )
                                                ],
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
