# Generated by Django 3.1.6 on 2021-04-13 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0003_datareportdetailarchivedetailpage_datareportdetailarchivelistpage",
        ),
        ("wagtailforms", "0004_add_verbose_name_plural"),
        ("wagtailmenus", "0023_remove_use_specific"),
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("emergency_response", "0002_heatindexpage_volunteerpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteerpage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="HeatIndexPage",
        ),
        migrations.DeleteModel(
            name="VolunteerPage",
        ),
    ]
