# Generated by Django 3.2.16 on 2022-10-25 14:52

from django.db import migrations

import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_response', '0003_remove_volunteerpage_heatindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyresponsepage',
            name='sections_of_links',
            field=wagtail.fields.StreamField([('section_of_links', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='The title for this section.', max_length=255, required=True)), ('number_of_columns', wagtail.blocks.IntegerBlock(default=1, help_text='The number of columns in which to show this section.', max_value=2, min_value=1)), ('link_blocks', wagtail.blocks.StreamBlock([('block_of_links', wagtail.blocks.StructBlock([('subtitle', wagtail.blocks.CharBlock(help_text='The subtitle for this block of links.', max_length=255, required=True)), ('text', wagtail.blocks.RichTextBlock())], blank=True))], required=False))]))], blank=True, use_json_field=True),
        ),
    ]
