ANIMAL_VETERINARY_CLINICS = "AV"
BUSINESSES_COMMUNITY_ORGANIZATIONS = "BCO"
CHILDCARE_SERVICES_DAYCARES = "CSD"
DENTAL_OFFICES_CLINICS = "DOC"
HOSPITALS_HEALTHCARE = "HH"
NURSING_PERSONAL_CARE_HOMES = "NPH"
PDPH_INTERNAL = "PDPH"
PHARMACY = "P"
PUBLIC_HEALTH_REGIONAL_PARTNERS = "PHRP"
UNIVERSITY_STUDENT_HEALTH = "USH"
OTHER = "O"
AGENCY_TYPE_CHOICES = [
    (ANIMAL_VETERINARY_CLINICS, "Animal and Veterinary Clinics"),
    (BUSINESSES_COMMUNITY_ORGANIZATIONS, "Businesses and Community Organizations"),
    (CHILDCARE_SERVICES_DAYCARES, "Child Care Services and Daycares"),
    (DENTAL_OFFICES_CLINICS, "Dental Offices and Clinics"),
    (HOSPITALS_HEALTHCARE, "Hospitals and Healthcare"),
    (NURSING_PERSONAL_CARE_HOMES, "Nursing and Personal Care Homes"),
    (PDPH_INTERNAL, "PDPH (Internal)"),
    (PHARMACY, "Pharmacy"),
    (PUBLIC_HEALTH_REGIONAL_PARTNERS, "Public Health and Regional Partners"),
    (UNIVERSITY_STUDENT_HEALTH, "University and Student Health"),
    (OTHER, "Other"),
]
