# Generated by Django 3.1.6 on 2021-02-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecontrolpage',
            name='page_type',
            field=models.IntegerField(choices=[(1, 'Topic Specific Guidance'), (2, 'Facility Specific Guidance'), (3, 'Disease Control Services')], help_text='Under which sub-heading does this page go?'),
        ),
    ]
