# Generated by Django 3.1.6 on 2021-02-27 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disease_control", "0002_auto_20210226_1804"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseasesAndConditionsPage",
            fields=[
                (
                    "diseasecontrolpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="disease_control.diseasecontrolpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("disease_control.diseasecontrolpage",),
        ),
    ]
