# Generated by Django 3.1.6 on 2021-03-01 12:01

import django.db.models.deletion
from django.db import migrations, models

import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0060_fix_workflow_unique_constraint"),
        ("disease_control", "0003_diseasesandconditionspage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseasePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("description", wagtail.core.fields.RichTextField(blank=True)),
                (
                    "is_emergent",
                    models.BooleanField(
                        default=False,
                        help_text="Should this disease be tagged as emergent?",
                    ),
                ),
                (
                    "emergent_begin_date",
                    models.DateField(
                        blank=True,
                        help_text="Choose the date this disease became an emergent concern",
                        null=True,
                    ),
                ),
                (
                    "emergent_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Choose the date this disease stopped being an emergent concern. Leave blank if it is still an emergent concern.",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
