# Generated by Django 3.1.6 on 2021-03-05 19:48

from django.db import migrations

import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('disease_control', '0004_diseasepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasepage',
            old_name='description',
            new_name='at_a_glance',
        ),
        migrations.AddField(
            model_name='diseasepage',
            name='current_recommendations',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='diseasepage',
            name='diagnosis_info',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='diseasepage',
            name='provider_resources',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='List resources that will be useful for healthcare providers. Resources for patients and community will be pulled automatically by including any documents that are tagged with the title of this disease/condition'),
        ),
        migrations.AddField(
            model_name='diseasepage',
            name='surveillance',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='diseasepage',
            name='vaccine_info',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
