# Generated by Django 3.1.6 on 2021-03-10 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('health_alerts', '0005_auto_20210310_1302'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disease_control', '0007_auto_20210310_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiseasePage',
            new_name='DiseaseAndConditionDetailPage',
        ),
    ]
