# Generated by Django 3.1.6 on 2021-03-10 18:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disease_control', '0008_auto_20210310_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmergentHealthTopicsPage',
            new_name='EmergentHealthTopicListPage',
        ),
    ]
