# Generated by Django 3.1.6 on 2021-04-07 12:21

import django.db.models.deletion
from django.db import migrations, models

import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks

import apps.hip.models


class Migration(migrations.Migration):

    dependencies = [
        ("disease_control", "0010_auto_20210310_1322"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseControlChildListPage",
            fields=[
                (
                    "diseasecontrolpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="disease_control.diseasecontrolpage",
                    ),
                ),
                (
                    "show_breadcrumb",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Should this page show a breadcrumb at the top of the page?",
                    ),
                ),
                (
                    "show_right_nav",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Should this page show a navigation of its sections on the right side of the page?",
                    ),
                ),
                (
                    "list_section",
                    wagtail.fields.StreamField(
                        [
                            (
                                "list_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "header",
                                            wagtail.blocks.CharBlock(
                                                help_text="The heading for this section of rows (maximum of 80 characters).",
                                                max_length=80,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "show_header_in_right_nav",
                                            wagtail.blocks.BooleanBlock(
                                                default=True,
                                                help_text="Should this header be shown in the navigation on the right side of the page?",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "rows",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "rows",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "page",
                                                                    wagtail.blocks.PageChooserBlock(
                                                                        help_text="An internal page",
                                                                        required=True,
                                                                    ),
                                                                ),
                                                                (
                                                                    "description",
                                                                    wagtail.blocks.RichTextBlock(
                                                                        help_text="Description for this row",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    )
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("disease_control.diseasecontrolpage",),
        ),
        migrations.CreateModel(
            name="DiseaseControlChildStaticPage",
            fields=[
                (
                    "diseasecontrolpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="disease_control.diseasecontrolpage",
                    ),
                ),
                (
                    "show_left_nav",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="Should this page show a navigation of the site on the left side of the page?",
                    ),
                ),
                (
                    "show_breadcrumb",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Should this page show a breadcrumb at the top of the page?",
                    ),
                ),
                (
                    "show_back_button",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Should this page show a back button at the top of the page?",
                    ),
                ),
                (
                    "show_right_nav",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Should this page show a navigation of its sections on the right side of the page?",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "nav_heading",
                                            wagtail.blocks.CharBlock(
                                                help_text="The heading that should appear for this section in the scrolling navigation on the side of the page.",
                                                max_length=80,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "is_card",
                                            wagtail.blocks.BooleanBlock(
                                                help_text="Is this content block a card?",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "body",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "rich_text",
                                                        wagtail.blocks.RichTextBlock(),
                                                    ),
                                                    (
                                                        "two_column_table",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "has_grid_pattern",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        help_text="Does this table's styling have a grid pattern?",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "is_first_row_header",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        help_text="Should the first row be displayed as a header?",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "rows",
                                                                    wagtail.blocks.StreamBlock(
                                                                        [
                                                                            (
                                                                                "rows",
                                                                                wagtail.blocks.StructBlock(
                                                                                    [
                                                                                        (
                                                                                            "column_1",
                                                                                            wagtail.blocks.RichTextBlock(
                                                                                                help_text="Text for column 1",
                                                                                                max_length=255,
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "column_2",
                                                                                            wagtail.blocks.RichTextBlock(
                                                                                                help_text="Text for column 2",
                                                                                                max_length=255,
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                    ]
                                                                                ),
                                                                            )
                                                                        ]
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "three_column_table",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "has_grid_pattern",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        help_text="Does this table's styling have a grid pattern?",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "is_first_row_header",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        help_text="Should the first row be displayed as a header?",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "rows",
                                                                    wagtail.blocks.StreamBlock(
                                                                        [
                                                                            (
                                                                                "rows",
                                                                                wagtail.blocks.StructBlock(
                                                                                    [
                                                                                        (
                                                                                            "column_1",
                                                                                            wagtail.blocks.RichTextBlock(
                                                                                                help_text="Text for column 1",
                                                                                                max_length=255,
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "column_2",
                                                                                            wagtail.blocks.RichTextBlock(
                                                                                                help_text="Text for column 2",
                                                                                                max_length=255,
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "column_3",
                                                                                            wagtail.blocks.RichTextBlock(
                                                                                                help_text="Text for column 3",
                                                                                                max_length=255,
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                    ]
                                                                                ),
                                                                            )
                                                                        ]
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "four_column_table",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "has_grid_pattern",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        help_text="Does this table's styling have a grid pattern?",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "is_first_row_header",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        help_text="Should the first row be displayed as a header?",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "rows",
                                                                    wagtail.blocks.StreamBlock(
                                                                        [
                                                                            (
                                                                                "rows",
                                                                                wagtail.blocks.StructBlock(
                                                                                    [
                                                                                        (
                                                                                            "column_1",
                                                                                            wagtail.blocks.RichTextBlock(
                                                                                                help_text="Text for column 1",
                                                                                                max_length=255,
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "column_2",
                                                                                            wagtail.blocks.RichTextBlock(
                                                                                                help_text="Text for column 2",
                                                                                                max_length=255,
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "column_3",
                                                                                            wagtail.blocks.RichTextBlock(
                                                                                                help_text="Text for column 3",
                                                                                                max_length=255,
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "column_4",
                                                                                            wagtail.blocks.RichTextBlock(
                                                                                                help_text="Text for column 4",
                                                                                                max_length=255,
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                    ]
                                                                                ),
                                                                            )
                                                                        ]
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "five_column_table",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "has_grid_pattern",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        help_text="Does this table's styling have a grid pattern?",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "is_first_row_header",
                                                                    wagtail.blocks.BooleanBlock(
                                                                        help_text="Should the first row be displayed as a header?",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                                (
                                                                    "rows",
                                                                    wagtail.blocks.StreamBlock(
                                                                        [
                                                                            (
                                                                                "rows",
                                                                                wagtail.blocks.StructBlock(
                                                                                    [
                                                                                        (
                                                                                            "column_1",
                                                                                            wagtail.blocks.RichTextBlock(
                                                                                                help_text="Text for column 1",
                                                                                                max_length=255,
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "column_2",
                                                                                            wagtail.blocks.RichTextBlock(
                                                                                                help_text="Text for column 2",
                                                                                                max_length=255,
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "column_3",
                                                                                            wagtail.blocks.RichTextBlock(
                                                                                                help_text="Text for column 3",
                                                                                                max_length=255,
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "column_4",
                                                                                            wagtail.blocks.RichTextBlock(
                                                                                                help_text="Text for column 4",
                                                                                                max_length=255,
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                        (
                                                                                            "column_5",
                                                                                            wagtail.blocks.RichTextBlock(
                                                                                                help_text="Text for column 5",
                                                                                                max_length=255,
                                                                                                required=False,
                                                                                            ),
                                                                                        ),
                                                                                    ]
                                                                                ),
                                                                            )
                                                                        ]
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                        (
                                            "contact_info",
                                            wagtail.snippets.blocks.SnippetChooserBlock(
                                                apps.hip.models.Contact, required=False
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("disease_control.diseasecontrolpage",),
        ),
    ]
