# Generated by Django 3.1.6 on 2021-04-07 12:23

from django.db import migrations

import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "disease_control",
            "0011_diseasecontrolchildlistpage_diseasecontrolchildstaticpage",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="diseasecontrolpage",
            name="description",
            field=wagtail.core.fields.RichTextField(
                blank=True,
                help_text="Text that that will show up as a description of this page on the disease control list page.",
            ),
        ),
    ]
