---
- name: kubernetes cluster management
  hosts: cluster
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  gather_facts: false
  roles:
    - role: caktus.k8s-web-cluster
