- name: caktus hosting services
  hosts: production
  gather_facts: false
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
    - role: caktus.k8s-hosting-services