---

- src: https://github.com/caktus/ansible-role-django-k8s
  name: caktus.django-k8s
  version: v0.0.7

- src: https://github.com/caktus/ansible-role-aws-web-stacks
  name: caktus.aws-web-stacks
  version: ''

- src: https://github.com/caktus/ansible-role-k8s-web-cluster
  name: caktus.k8s-web-cluster
  version: v0.0.7
