---
roles:
  - src: https://github.com/caktus/ansible-role-aws-web-stacks
    name: caktus.aws-web-stacks
    version: v0.3.0
  - src: https://github.com/caktus/ansible-role-k8s-web-cluster
    version: v1.10.1
    name: caktus.k8s-web-cluster
  - src: https://github.com/caktus/ansible-role-django-k8s
    name: caktus.django-k8s
    version: v1.12.1
  - src: https://github.com/caktus/ansible-role-k8s-hosting-services
    name: caktus.k8s-hosting-services
    version: v0.13.0

  - src: weareinteractive.users
    version: 1.17.0

collections:
  - name: amazon.aws
    version: 8.2.1
