# Generated by Django 5.1.7 on 2025-03-19 15:05

from django.db import migrations, models


# Support for CIEmailField was be depreacated after Django 4.2 in favor
# of vanilla EmailField. Below is how to migrate to the vanilla EmailField whilst
# creating a non-deterministic collation. See Adam's post for more information
# https://adamj.eu/tech/2023/02/23/migrate-django-postgresql-ci-fields-case-insensitive-collation/
class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_first_last_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_collation="case_insensitive", max_length=255, unique=True
            ),
        ),
    ]
