# Generated by Django 3.1.6 on 2021-02-19 18:10

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('health_alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAlertPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('priority', models.IntegerField(choices=[(1, 'Update'), (2, 'Notification'), (3, 'Advisory'), (4, 'Alert')])),
                ('alert_date', models.DateField(default=datetime.date.today)),
                ('alert_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
