# Generated by Django 3.1.6 on 2021-03-15 00:12

import django.core.validators
from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('health_alerts', '0003_healthalertpage_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAlertsSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_first_name', models.CharField(default='', max_length=255, verbose_name='First Name')),
                ('personal_last_name', models.CharField(default='', max_length=255, verbose_name='Last Name')),
                ('personal_medical_expertise', models.CharField(default='', max_length=255, verbose_name='Medical Specialty/Expertise')),
                ('personal_professional_license', models.CharField(default='', max_length=255, verbose_name='Professional License')),
                ('agency_name', models.CharField(default='', max_length=255)),
                ('agency_type', models.CharField(choices=[('AV', 'Animal and Veterinary Clinics'), ('BCO', 'Businesses and Community Organizations'), ('CSD', 'Child Care Services and Daycares'), ('DOC', 'Dental Offices and Clinics'), ('HH', 'Hospitals and Healthcare'), ('NPH', 'Nursing and Personal Care Homes'), ('PDPH', 'PDPH (Internal)'), ('P', 'Pharmacy'), ('PHRP', 'Public Health and Regional Partners'), ('USH', 'University and Student Health'), ('O', 'Other')], max_length=4)),
                ('agency_zip_code', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{5}(?:-[0-9]{4})?$', 'Either provide a 5 or 9 digit zipcode Ex: 12345 or 12345-1234')])),
                ('agency_position', models.CharField(default='', max_length=255, verbose_name='Position/Title')),
                ('agency_work_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Work Phone (optional)')),
                ('network_email', models.EmailField(default='', max_length=254, verbose_name='Email Address')),
                ('network_fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Fax Number')),
            ],
        ),
    ]
