# Generated by Django 3.1.6 on 2021-03-10 18:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('health_alerts', '0003_healthalertpage_disease'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthAlertIndexPage',
            new_name='HealthAlertListPage',
        ),
    ]
