# Generated by Django 3.1.6 on 2021-03-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_alerts', '0004_healthalertssignup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthalertssignup',
            options={'verbose_name': 'Health Alerts Subscriber', 'verbose_name_plural': 'Health Alerts Subscribers'},
        ),
    ]
