# Generated by Django 3.1.6 on 2021-03-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_alerts', '0005_auto_20210316_0655'),
        ('health_alerts', '0005_auto_20210310_1302'),
    ]

    operations = [
    ]
