# Generated by Django 3.1.6 on 2021-03-19 20:59

import django.core.validators
from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('health_alerts', '0006_healthalertsubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthalertsubscriber',
            name='agency_name',
            field=models.CharField(default='', max_length=255, verbose_name='Agency Name*'),
        ),
        migrations.AlterField(
            model_name='healthalertsubscriber',
            name='agency_position',
            field=models.CharField(default='', max_length=255, verbose_name='Position/Title*'),
        ),
        migrations.AlterField(
            model_name='healthalertsubscriber',
            name='agency_type',
            field=models.CharField(choices=[('AV', 'Animal and Veterinary Clinics'), ('BCO', 'Businesses and Community Organizations'), ('CSD', 'Child Care Services and Daycares'), ('DOC', 'Dental Offices and Clinics'), ('HH', 'Hospitals and Healthcare'), ('NPH', 'Nursing and Personal Care Homes'), ('PDPH', 'PDPH (Internal)'), ('P', 'Pharmacy'), ('PHRP', 'Public Health and Regional Partners'), ('USH', 'University and Student Health'), ('O', 'Other')], max_length=4, verbose_name='Agency Type*'),
        ),
        migrations.AlterField(
            model_name='healthalertsubscriber',
            name='agency_work_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Work Phone'),
        ),
        migrations.AlterField(
            model_name='healthalertsubscriber',
            name='agency_zip_code',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{5}(?:-[0-9]{4})?$', 'Either provide a 5 or 9 digit zipcode Ex: 12345 or 12345-1234')], verbose_name='Agency Zip Code*'),
        ),
        migrations.AlterField(
            model_name='healthalertsubscriber',
            name='network_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email Address*'),
        ),
        migrations.AlterField(
            model_name='healthalertsubscriber',
            name='network_fax',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Fax Number*'),
        ),
        migrations.AlterField(
            model_name='healthalertsubscriber',
            name='personal_first_name',
            field=models.CharField(default='', max_length=255, verbose_name='First Name*'),
        ),
        migrations.AlterField(
            model_name='healthalertsubscriber',
            name='personal_last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Last Name*'),
        ),
        migrations.AlterField(
            model_name='healthalertsubscriber',
            name='personal_medical_expertise',
            field=models.CharField(default='', max_length=255, verbose_name='Medical Specialty/Expertise*'),
        ),
        migrations.AlterField(
            model_name='healthalertsubscriber',
            name='personal_professional_license',
            field=models.CharField(default='', max_length=255, verbose_name='Professional License*'),
        ),
    ]
