# Generated by Django 3.2.5 on 2022-01-18 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hip', '0022_create_button_snippets_for_forms'),
        ('posters', '0002_alter_posterdetailpage_main_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posterdocumentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hip.hipdocument'),
        ),
    ]
