---
##  users role configuration ##
users_groups: [adm, dialout, docker, sudo]
users_shell: /bin/bash

# when removing a user, add their username to this list:
users_remove:
  # Remove default user installed by Ubuntu. You might need to comment this out
  # temporarily when first configuring a server, and possibly even reboot the
  # server before the user can be removed.
  - ubuntu

# users to provision on all servers
# find your ssh key with: `cat ~/.ssh/id_*.pub` (should be one line)
# optionally generate password via `mkpasswd -m sha-512 -R 2000000`
users:
  # in alphabetical order
  - username: copelco
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICMtpiB+QFK/YDEx3qiq62zUcxKOiuIOe1CNmD+NQYKt copelco@caktusgroup.com
  - username: ronardlunagerman
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEhNwSFktLJpdP/e04FPZxEwXsZyqTi8URd2IBjuw0Je rluna@caktusgroup.com
  - username: tobias
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFti2WxKH5TJh6SN44pkvG2V4268sJfirn00YrKLy+lY tobias@red-ed25519

# On GitHub
github_pat: "{{ lookup('env', 'RUNNER_CFG_PAT') }}"
github_scope: caktus

# On the VM
github_runner_user: runner
github_runner_name: philly-hip-runner
github_runner_location: philly-hip