name: Deploy to k8s cluster

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      # https://github.com/marketplace/actions/slack-github-actions-slack-integration
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/**.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        id: pip-install
        run: |
          python -m pip install --upgrade pip wheel pip-tools
          pip-sync requirements/base/base.txt requirements/dev/dev.txt
      - name: Login to Docker
        id: docker-login
        run: |
          inv aws.docker-login
      - name: Build, tag, push, and deploy image
        id: build-tag-push-deploy
        run: |
          [ "$GITHUB_REF" = refs/heads/main ] &&
            ENV="production" ||
            ENV="staging"
          echo "env is $ENV"
          inv $ENV image deploy --verbosity=0
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        # always() means to notify regardless of status
        if: always()
