# Generated by Django 3.1.8 on 2021-06-11 20:28

import django.core.validators
from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityResponseSubscriber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="First Name*"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Last Name*"
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Organization Name*"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=255, verbose_name="Title/Position*"
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(max_length=254, verbose_name="Email Address*"),
                ),
                (
                    "cell_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Cell Phone*"
                    ),
                ),
                (
                    "organization_street_address",
                    models.CharField(
                        max_length=255, verbose_name="Street Address of Organization*"
                    ),
                ),
                (
                    "organization_po_box",
                    models.CharField(
                        max_length=255,
                        verbose_name="Organization PO Box",
                        blank=True,
                    ),
                ),
                (
                    "organization_zip_code",
                    models.CharField(
                        default="",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{5}(?:-[0-9]{4})?$",
                                "Either provide a 5 or 9 digit zipcode Ex: 12345 or 12345-1234",
                            )
                        ],
                        verbose_name="Zip Code of Organization*",
                    ),
                ),
                (
                    "organization_zip_codes_served",
                    models.CharField(
                        default="",
                        max_length=255,
                        verbose_name="Zip Codes Served by Your Organization*",
                    ),
                ),
                (
                    "organization_community_members_served",
                    models.CharField(
                        choices=[
                            ("Children/Youth", "Children/Youth"),
                            ("Older Adults", "Older Adults"),
                            (
                                "Marginalized racial or ethnic group",
                                "Marginalized racial or ethnic group",
                            ),
                            ("Immigrant", "Immigrant"),
                            (
                                "refugee or undocumented communities",
                                "refugee or undocumented communities",
                            ),
                            (
                                "Gender non-conforming/non-binary",
                                "Gender non-conforming/non-binary",
                            ),
                            ("LGBTQ+", "LGBTQ+"),
                            ("Unemployed", "Unemployed"),
                            ("Uninsured/Underinsured", "Uninsured/Underinsured"),
                            ("Experiencing homelessness", "Experiencing homelessness"),
                            ("Low-income communities", "Low-income communities"),
                            ("People with disabilities", "People with disabilities"),
                            ("People who are homebound", "People who are homebound"),
                            (
                                "Living with a mental illness",
                                "Living with a mental illness",
                            ),
                            (
                                "Living with a substance use disorder",
                                "Living with a substance use disorder",
                            ),
                            ("Chronically ill", "Chronically ill"),
                            ("Returning citizens", "Returning citizens"),
                            ("Currently incarcerated", "Currently incarcerated"),
                            ("Faith communities", "Faith communities"),
                            (
                                "Minimal to no digital access",
                                "Minimal to no digital access",
                            ),
                            ("Pregnant", "Pregnant"),
                            ("Single parent", "Single parent"),
                            ("Veterans", "Veterans"),
                            (
                                "Limited English proficient",
                                "Limited English proficient",
                            ),
                            ("Caregiver dependent", "Caregiver dependent"),
                            (
                                "No access to private vehicle",
                                "No access to private vehicle",
                            ),
                            (
                                "Dependent on prescription medications",
                                "Dependent on prescription medications",
                            ),
                            (
                                "Living in a congregate setting",
                                "Living in a congregate setting",
                            ),
                            ("Students", "Students"),
                            (
                                "Survivors of violence or abuse",
                                "Survivors of violence or abuse",
                            ),
                            ("Essential worker", "Essential worker"),
                            ("General public", "General public"),
                            ("Other", "Other"),
                            ("All of these", "All of these"),
                        ],
                        max_length=100,
                        verbose_name="Community Members Served by Your Organization*",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Community Response Subscribers"},
        ),
    ]
