# Generated by Django 3.1.8 on 2021-06-16 12:02

from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_communityresponsesubscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpioidOverdoseSubscriber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="First Name*"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Last Name*"
                    ),
                ),
                (
                    "medical_specialty",
                    models.CharField(
                        default="",
                        max_length=255,
                        verbose_name="Medical Specialty/Area of Expertise*",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Company Name*"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=255, verbose_name="Your Title/Position*"
                    ),
                ),
                (
                    "work_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Work Phone*"
                    ),
                ),
                (
                    "notification_group",
                    models.CharField(
                        choices=[
                            ("Agencies", "Agencies"),
                            ("Hospitals", "Hospitals"),
                            ("Community Members", "Community Members"),
                            ("Media/Press", "Media/Press"),
                        ],
                        max_length=100,
                        verbose_name="Notification Group*",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(max_length=254, verbose_name="Email Address*"),
                ),
                (
                    "mobile_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Mobile Phone*"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Opioid Overdose Subscribers",
            },
        ),
    ]
