# Generated by Django 3.1.8 on 2021-06-16 12:40

from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_opioidoverdosesubscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeRedCodeBlueSubscriber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="First Name*"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Last Name*"
                    ),
                ),
                (
                    "agency_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Agency Name*"
                    ),
                ),
                (
                    "work_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Work Phone*"
                    ),
                ),
                (
                    "work_email",
                    models.EmailField(max_length=254, verbose_name="Work Email*"),
                ),
                (
                    "cell_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Cell Phone*"
                    ),
                ),
                (
                    "personal_email",
                    models.EmailField(max_length=254, verbose_name="Personal Email*"),
                ),
            ],
            options={
                "verbose_name_plural": "Code Red/Code Blue Subscribers",
            },
        ),
    ]
