# Generated by Django 3.1.8 on 2021-06-17 13:05

import django.core.validators
from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_coderedcodebluesubscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicHealthPreparednessSubscriber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="First Name*"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Last Name*"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Phone Number*"
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(max_length=254, verbose_name="Email Address*"),
                ),
                (
                    "organization_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Organization Name*"
                    ),
                ),
                (
                    "organization_zip_code",
                    models.CharField(
                        default="",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{5}(?:-[0-9]{4})?$",
                                "Either provide a 5 or 9 digit zipcode Ex: 12345 or 12345-1234",
                            )
                        ],
                        verbose_name="Organization Zip Code*",
                    ),
                ),
                (
                    "outreach_request_choice",
                    models.CharField(
                        choices=[
                            ("Meeting", "Meeting"),
                            ("Training", "Training"),
                            ("Resource", "Resource"),
                        ],
                        max_length=10,
                        verbose_name="I would like to request a*",
                    ),
                ),
                (
                    "outreach_request_additional_info",
                    models.TextField(
                        blank=True,
                        verbose_name="Please provide additional information about your request below.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Public Health Preparedness Subscribers",
            },
        ),
    ]
