# Generated by Django 3.1 on 2021-06-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_publichealthpreparednesssubscriber"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OpioidOverdoseSubscriber",
            new_name="DrugOverdoseSubscriber",
        ),
        migrations.AlterModelOptions(
            name="drugoverdosesubscriber",
            options={"verbose_name_plural": "Drug Overdose Subscribers"},
        ),
    ]
