# Generated by Django 3.1 on 2021-06-22 19:35

from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_internal_alerts_new_division_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coderedcodebluesubscriber",
            name="agency_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Agency Name"
            ),
        ),
        migrations.AlterField(
            model_name="coderedcodebluesubscriber",
            name="cell_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Cell Phone"
            ),
        ),
        migrations.AlterField(
            model_name="coderedcodebluesubscriber",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="coderedcodebluesubscriber",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="coderedcodebluesubscriber",
            name="personal_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Personal Email"
            ),
        ),
        migrations.AlterField(
            model_name="coderedcodebluesubscriber",
            name="work_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Work Email"
            ),
        ),
        migrations.AlterField(
            model_name="coderedcodebluesubscriber",
            name="work_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Work Phone"
            ),
        ),
    ]
