# Generated by Django 3.1 on 2021-06-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_rename_opioid_overdose_subscriber_drug_overdose_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalemployeealertsubscriber",
            name="ambulatory_health_center",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Administration", "Administration"),
                    ("Health Center 2", "Health Center 2"),
                    ("Health Center 3", "Health Center 3"),
                    ("Health Center 4", "Health Center 4"),
                    ("Health Center 5", "Health Center 5"),
                    ("Health Center 6", "Health Center 6"),
                    ("Health Center 9", "Health Center 9"),
                    ("Health Center 10", "Health Center 10"),
                    (
                        "Health Center Strawberry Mansion",
                        "Health Center Strawberry Mansion",
                    ),
                ],
                max_length=100,
                verbose_name="Ambulatory Health Center*",
            ),
        ),
        migrations.AddField(
            model_name="internalemployeealertsubscriber",
            name="disease_control_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Administration", "Administration"),
                    ("Acute Communicable Disease", "Acute Communicable Disease"),
                    ("Bioterrorism", "Bioterrorism"),
                    ("Epidemiology", "Epidemiology"),
                    ("Health Center 1", "Health Center 1"),
                    ("Health Center 5", "Health Center 5"),
                    ("Immunizations", "Immunizations"),
                    ("STD Control", "STD Control"),
                    ("Support Staff", "Support Staff"),
                    ("Tuberculosis", "Tuberculosis"),
                    ("Hepatitis", "Hepatitis"),
                    ("HAI-AR", "HAI-AR"),
                ],
                max_length=100,
                verbose_name="Disease Control Program*",
            ),
        ),
        migrations.AddField(
            model_name="internalemployeealertsubscriber",
            name="ehs_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Administration", "Administration"),
                    ("Environmental Engineering", "Environmental Engineering"),
                    ("Food Protection", "Food Protection"),
                    ("Vector Control", "Vector Control"),
                    ("Childhood Lead", "Childhood Lead"),
                ],
                max_length=100,
                verbose_name="EHS Program*",
            ),
        ),
    ]
