# Generated by Django 4.2.14 on 2025-01-01 00:02

from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_coderedcodebluesubscriber_fields_are_optional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communityresponsesubscriber",
            name="organization_po_box",
        ),
        migrations.RemoveField(
            model_name="communityresponsesubscriber",
            name="organization_street_address",
        ),
        migrations.RemoveField(
            model_name="communityresponsesubscriber",
            name="organization_zip_codes_served",
        ),
        migrations.RemoveField(
            model_name="communityresponsesubscriber",
            name="title",
        ),
        migrations.AddField(
            model_name="communityresponsesubscriber",
            name="organization_mission_statement",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Mission Statement"
            ),
        ),
        migrations.AddField(
            model_name="communityresponsesubscriber",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("Arts and Culture", "Arts and Culture"),
                    ("Block Captain", "Block Captain"),
                    (
                        "Civic Engagement/Elected Official",
                        "Civic Engagement/Elected Official",
                    ),
                    (
                        "Disabilities and Access and Functional Needs",
                        "Disabilities and Access and Functional Needs",
                    ),
                    (
                        "Education (Schools/Colleges/Universities)",
                        "Education (Schools/Colleges/Universities)",
                    ),
                    ("Free Library of Philadelphia", "Free Library of Philadelphia"),
                    ("General Community Services", "General Community Services"),
                    ("Healthcare", "Healthcare"),
                    (
                        "Immigrante/Refugee/Communities that speak languages other than English",
                        "Immigrante/Refugee/Communities that speak languages other than English",
                    ),
                    ("Live Bird Market", "Live Bird Market"),
                    ("Mental/Behavioral Health", "Mental/Behavioral Health"),
                    ("Older Adults", "Older Adults"),
                    ("Housing/Homeless Services", "Housing/Homeless Services"),
                    ("RCO/CDC/NAC", "RCO/CDC/NAC"),
                    ("Recreational", "Recreational"),
                    ("Religious/Faith-based", "Religious/Faith-based"),
                    ("Workers", "Workers"),
                    ("Youth", "Youth"),
                    ("Unaffiliated Community Leader", "Unaffiliated Community Leader"),
                ],
                default="",
                max_length=255,
                verbose_name="Organization Type*",
            ),
        ),
        migrations.AlterField(
            model_name="communityresponsesubscriber",
            name="cell_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Cell Phone"
            ),
        ),
        migrations.AlterField(
            model_name="communityresponsesubscriber",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="communityresponsesubscriber",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Last Name"
            ),
        ),
    ]
